apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: converter-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vidcast-parameter-store
    kind: ClusterSecretStore
  target:
    name: converter-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: MONGODB_URI
      remoteRef:
        key: /vidcast/dev/converter/mongodb-uri
