apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gateway-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vidcast-parameter-store
    kind: ClusterSecretStore
  target:
    name: gateway-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: MONGODB_VIDEOS_URI
      remoteRef:
        key: /vidcast/dev/gateway/mongodb-videos-uri
    - secretKey: MONGODB_MP3S_URI
      remoteRef:
        key: /vidcast/dev/gateway/mongodb-mp3s-uri
