apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notification-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vidcast-parameter-store
    kind: ClusterSecretStore
  target:
    name: notification-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: GMAIL_ADDRESS
      remoteRef:
        key: /vidcast/prod/notification/gmail-address
    - secretKey: GMAIL_PASSWORD
      remoteRef:
        key: /vidcast/prod/notification/gmail-password
