apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vidcast-parameter-store
    kind: ClusterSecretStore
  target:
    name: auth-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: /vidcast/prod/auth/psql-password
    - secretKey: JWT_SECRET
      remoteRef:
        key: /vidcast/prod/auth/jwt-secret
