apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: {{ .Values.secret.default_user | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.secret.default_pass | quote }}
