apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
  template:
    metadata:
      labels:
        app: notification
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      volumes:
        - name: tmp-volume
          emptyDir: {}
      containers:
        - name: notification
          image: johnbaabalola/notification-service:16f49a0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: notification-configmap
            - secretRef:
                name: notification-secret
            - secretRef:
                name: rabbitmq-secret
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          livenessProbe:
            exec:
              command: ["test", "-f", "/tmp/healthy"]
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
